curl -X 'POST' \
  /api/messages/text \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {TOKEN}' \
  -d '{
  "to": "917838418898",
  "body": "Hello, this message was sent via API!"
}'


